chartKind: vertical_bar
config:
  display: {}
  fieldConfig:
    groupBy: []
    sortBy:
      - direction: ASC
        reference: OBJECT_TYPE
    x:
      reference: OBJECT_TYPE
      type: category
    "y":
      - aggregation: sum
        reference: CLICKOUTS
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: ""
limit: 500
name: Movie vs Show split per segment
slug: movie-vs-show-split-per-segment
spaceSlug: test
sql: |-
  SELECT u.segment_name, c.object_type, COUNT(*) AS clickouts
  FROM DB_TEAM_8.BASE_MART.FCT_EVENTS f
  JOIN DB_TEAM_8.BASE_MART.DIM_USERS u ON f.user_id = u.user_id
  JOIN DB_TEAM_8.BASE_MART.DIM_CONTENT c ON f.title_id = c.title_id
  WHERE f.is_clickout = TRUE
  GROUP BY 1,2 ORDER BY 1,3 DESC
version: 1
