chartKind: vertical_bar
config:
  display: {}
  fieldConfig:
    groupBy: []
    sortBy:
      - direction: ASC
        reference: PROVIDER_GROUP
    x:
      reference: PROVIDER_GROUP
      type: category
    "y":
      - aggregation: sum
        reference: CLICKOUTS
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: ""
limit: 500
name: Provider Leaderboard
slug: provider-leaderboard
spaceSlug: test
sql: >
  SELECT pm.provider_group, COUNT(*) AS clickouts, COUNT(DISTINCT f.user_id) AS
  unique_users

  FROM DB_TEAM_8.BASE_MART.FCT_EVENTS f

  JOIN DB_TEAM_8.REFERENCE.PROVIDER_MAPPING pm ON pm.provider_id = f.provider_id

  WHERE f.is_clickout = TRUE

  GROUP BY 1 ORDER BY 2 DESC LIMIT 20
version: 1
